### ISSUE TITLE
유저가 검색한 장소를 위한 모델 설계 및 구현

### ISSUE THREAD

**Issue by KsPsD** [f-lab-edu/Meet-Up-Spot#13]
# DESCRIPTION
유저가 검색한 장소를 위한 모델 추가하고  user_preferences 내용을 추가해야함

# TODO
- [x] UserSearchedPlace 테이블 설계 및 구현. 
- [x] user_preferences 어떻게 설정할지 정해야함
- [x] 관련 API 및 로직 업데이트

#  ETC
지금 기획에서는 검색 자체가 주소와 선호사항을 받아서 되는데 이 주소를 통해 찾은 장소로 저장할 계획

**Comment by KsPsD** [comment]
유저 Location history 관계 모델 추가 및 관련된 코드 리팩토링 #16  에서 추가함
