### ISSUE TITLE
사용자의 현재 위치 저장하기 위한 모델 설계 및 구현

### ISSUE THREAD

**Issue by KsPsD** [f-lab-edu/Meet-Up-Spot#14]
# DESCRIPTION
사용자의 현재 위치 저장하기 위한 모델 설계 및 구현하고 관련 recommend_places 로직 개선

# TODO
- [ ] UserLocation 모델 설계 및 구현
- [ ] UserLocation 정보를 저장하는 엔드포인트 개발
- [ ] recommend_places 로직에 UserLocation 정보를 활용하여 추천 알고리즘 개선
- [ ] 테스트 및 피드백을 통한 반복적인 개선

#  ETC
